name: eventlogs-channel-delete
trigger: channelDelete
conditions:
  - id: textLengthAbove
    args:
      text: "%meta_event_log_channel%"
      amount: 0
actions:
  - id: sendMessage
    target:
      channel: "%meta_event_log_channel%"
    args:
      components:
        - type: container
          color: "#5865f2"
          components:
            - type: text-display
              content: "## Channel Deleted"
            - type: text-display
              content: "**Name:** `%channel_name%`\n**Type:** `%channel_type%`\n**ID:** `%channel_id%`"
            - type: separator
              spacing: 1
            - type: text-display
              content: "Channel Deleted - %date% at %hour%:%minute%"
